server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost/subtlechat
    type: com.alibaba.druid.pool.DruidDataSource
    username: test
    password: 123456
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

fastdfs:
  nginx:
    host:



