server:
  port: 8084
#邮件相关配置
spring:
  application:
    name: subtlechat-mailserver
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    #邮箱名
    username: yumenghu@foxmail.com
    #申请的授权码
    password: kvrjjwufpanmibcb
    port: 587
    properties:
      mail.stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.debug: true
  #RabbitMQ的配置
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    #开启手动确认是否消息消费成功
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  #Redis的配置
  redis:
    database: 0
    password: 12345678
    host: localhost
    port: 6379
